os: osx
language: ruby
rvm: 2.1.3
sudo: false

cache: 
  - bundler

before_script:
  - npm install -g markdown-link-check

script:
  - set -o pipefail
  - bundle exec jekyll build --future --drafts
  - bundle exec danger
  - find . -name "*.md" | while read filename; do
        echo "Searching $filename";
        cat "$filename" | markdown-link-check;
    done
